### PR TITLE
Bugs/pip fails verification for 254mib piece

### LINKED ISSUE #750: sealing 256MiB sector always fails with "pip verification sanity check failed"
### Description

Sealing a 256MiB sector results in a panic with the message "pip verification sanity check failed."

To reproduce the issue, check out the `bugs/pip-fails-verification-for-254mib-piece` and run the following command:

```
cargo test --color=always --release --package filecoin-proofs --lib api::tests::test_pip_lifecycle -- --nocapture --exact --ignored
```

I have reproduced this issue after writing a 1 byte piece to a staged sector and then sealing. I have reproduced the issue with a single 266338304 byte piece (the max that can fit into a 256MiB sector before padding). Same thing with a 266338303 byte piece (1 less byte than the max that can fit into a 256MiB sector before padding).

Full output from a recent build as follows:

```
/Users/erinswenson-healey/.cargo/bin/cargo test --color=always --release --package filecoin-proofs --lib api::tests::test_pip_lifecycle -- --nocapture --exact --ignored
    Finished release [optimized] target(s) in 0.28s
     Running target/release/deps/filecoin_proofs-04f506004cf137f2

running 1 test
test api::tests::test_pip_lifecycle ... test api::tests::test_pip_lifecycle has been running for over 60 seconds
Jul 19 16:38:41.826 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 16:40:10.099 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 16:41:41.390 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 16:43:17.903 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 16:47:33.494 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 16:48:32.090 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 16:48:32.642 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 16:48:32.924 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 16:48:32.926 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 16:48:32.963 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 16:48:32.963 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 16:48:32.963 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 16:48:32.964 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 16:50:18.298 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 19 16:50:18.298 INFO no params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 19 16:50:18.299 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 8388608; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 19 16:50:18.300 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 19 16:50:18.300 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" for parameters, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:239 storage_proofs::parameter_cache
Jul 19 16:50:37.367 INFO read parameters from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" , target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:242 storage_proofs::parameter_cache
Jul 19 16:50:37.370 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Error: ErrorMessage { msg: "pip verification sanity check failed" }

stack backtrace:
   0: backtrace::backtrace::trace::h37db7b281e8eba34 (0x1092fd79c)
   1: backtrace::capture::Backtrace::new_unresolved::hb47bc0cd0d6f0c01 (0x1092fc988)
   2: failure::backtrace::internal::InternalBacktrace::new::hb6061924a8041047 (0x1092fc2d7)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::hc4825ecfc2df20ec (0x1092fc4c5)
   4: filecoin_proofs::api::seal::h9c82be9ec1e169f6 (0x109101f0a)
   5: filecoin_proofs::api::tests::test_pip_lifecycle::hea0088ab1a2d5c73 (0x109167bed)
   6: core::ops::function::FnOnce::call_once::hd71b9066e9446c9a (0x1090fa539)
   7: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h25930afafaaa1802 (0x10918a77e)
   8: ___rust_maybe_catch_panic (0x10931786f)
   9: test::run_test::run_test_inner::{{closure}}::hc15eafa796ce4688 (0x1091a3db7)
  10: std::sys_common::backtrace::__rust_begin_short_backtrace::ha78d88fbb27cfe1b (0x10917fb45)
  11: std::panicking::try::do_call::hb2f0e9992c7de429 (0x109183be5)
  12: ___rust_maybe_catch_panic (0x10931786f)
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}::h12bc3b8731d6ecee (0x1091841b5)
  14: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7164981f64385471 (0x10930777e)
  15: std::sys::unix::thread::Thread::new::thread_start::h450ce011087b0558 (0x109316ede)
  16: __pthread_body (0x7fff595482eb)
  17: __pthread_start (0x7fff5954b249)
thread 'api::tests::test_pip_lifecycle' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', src/libtest/lib.rs:334:5
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: std::panicking::begin_panic_fmt
   5: test::assert_test_result
   6: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
   7: __rust_maybe_catch_panic
   8: test::run_test::run_test_inner::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test api::tests::test_pip_lifecycle ... FAILED

failures:

failures:
    api::tests::test_pip_lifecycle

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 21 filtered out

error: test failed, to rerun pass '-p filecoin-proofs --lib'

Process finished with exit code 101
```

### PR DESCRIPTION
**Pull request by porcuquine**
Closes #750 .

@sidke or @laser may want to verify that my fix makes sense.

The branch provided in #750 (thanks @laser) took a really long time to run the test, so I first shrunk the sector size to something more minimal which still reproduced the issue. You may want to verify that before accepting this PR.

The problem seems to be that the sector size, in nodes, was being miscalculated. I think it was being treated as though unpadded, when actually padded. Or… something.

Feel free to fix this more robustly or just merge as-is. I didn't spend much time studying the logic behind what I changed once I eventually identified the source of the problem.

### CODE REVIEW

**Comment by laser** [comment]
I wrote a script which sealed sectors of various sizes (1024B, 64MiB, 256MiB, 1GiB), each which contained a randomly sized piece. It ran overnight and I saw no failures.

Also to note is that this is the first time I've sealed a 1GiB sector on my machine. It took about 43 minutes.

```
23:55 $ cargo test --color=always --release --package filecoin-proofs --lib api::tests::test_pip_lifecycle -- --nocapture --exact --ignored
    Finished release [optimized] target(s) in 0.15s
     Running target/release/deps/filecoin_proofs-04f506004cf137f2

running 1 test
writing 287B to piece-file
generating piece commitment for 1016B piece
writing 287B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 19 23:55:36.432 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:55:36.433 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:55:36.433 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:55:36.433 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:55:36.433 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:55:36.434 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:55:36.434 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:55:36.434 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:55:36.434 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:55:36.435 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:55:36.435 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:55:36.435 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:55:36.435 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:55:36.437 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 19 23:55:36.437 INFO no params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 19 23:55:36.437 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 32; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 19 23:55:36.437 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.params" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 19 23:55:36.437 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.params" for parameters, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:239 storage_proofs::parameter_cache
Jul 19 23:55:43.322 INFO read parameters from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.params" , target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:242 storage_proofs::parameter_cache
Jul 19 23:55:43.322 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 19 23:56:24.805 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 19 23:56:24.805 INFO no params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 19 23:56:24.805 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 32; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 19 23:56:24.805 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.vk" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 19 23:56:24.805 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.vk" for verifying key, target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:251 storage_proofs::parameter_cache
Jul 19 23:56:24.839 INFO read verifying key from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-6648cd509799c8b76f944bbc971692c69d1480fa60c569bfc1284f0bd8ead988.vk" , target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:254 storage_proofs::parameter_cache
Jul 19 23:56:24.839 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 14996B to piece-file
generating piece commitment for 16256B piece
writing 14996B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 19 23:56:24.905 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:56:24.909 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:56:24.913 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:56:24.919 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 19 23:56:24.930 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:56:24.938 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:56:24.938 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:56:24.938 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:56:24.939 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 19 23:56:24.939 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:56:24.939 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:56:24.939 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:56:24.939 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 19 23:56:24.948 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 19 23:56:24.948 INFO no params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 19 23:56:24.948 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 512; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 19 23:56:24.948 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.params" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 19 23:56:24.948 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.params" for parameters, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:239 storage_proofs::parameter_cache
Jul 19 23:56:34.087 INFO read parameters from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.params" , target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:242 storage_proofs::parameter_cache
Jul 19 23:56:34.087 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
test api::tests::test_pip_lifecycle ... test api::tests::test_pip_lifecycle has been running for over 60 seconds
Jul 19 23:57:29.915 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 19 23:57:29.915 INFO no params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 19 23:57:29.915 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 512; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 19 23:57:29.915 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.vk" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 19 23:57:29.916 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.vk" for verifying key, target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:251 storage_proofs::parameter_cache
Jul 19 23:57:29.950 INFO read verifying key from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-701b165d17077bf6ced8a1bc890d649c88e963df9c4f7ac3d52a53db5945f65f.vk" , target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:254 storage_proofs::parameter_cache
Jul 19 23:57:29.951 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
writing 92988400B to piece-file
generating piece commitment for 266338304B piece
writing 92988400B (unpadded) to 268435456B (padded) sector
sealing 268435456B (padded) sector
Jul 20 00:03:00.572 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:04:23.952 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:05:49.720 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:07:16.828 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:11:26.028 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:11:31.127 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:11:34.079 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:11:35.952 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:11:36.022 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:11:36.040 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:11:36.041 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:11:36.041 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:11:36.041 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:12:23.133 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:12:23.133 INFO no params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 20 00:12:23.133 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 8388608; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 20 00:12:23.133 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 20 00:12:23.134 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" for parameters, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:239 storage_proofs::parameter_cache
Jul 20 00:12:39.081 INFO read parameters from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.params" , target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:242 storage_proofs::parameter_cache
Jul 20 00:12:39.081 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 00:14:17.420 INFO trying parameters memory cache for: ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:14:17.420 INFO no params in memory cache for ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 20 00:14:17.420 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 8388608; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 20 00:14:17.420 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.vk" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 20 00:14:17.420 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.vk" for verifying key, target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:251 storage_proofs::parameter_cache
Jul 20 00:14:17.456 INFO read verifying key from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-56360c4554216174de15d2c76acbd0f360e0fabf07dd470ca50f7d39676e7874.vk" , target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:254 storage_proofs::parameter_cache
Jul 20 00:14:17.456 INFO got verifying key (268435456) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 268435456B (padded) sector
writing 24091413B to piece-file
generating piece commitment for 1065353216B piece
writing 24091413B (unpadded) to 1073741824B (padded) sector
sealing 1073741824B (padded) sector
Jul 20 00:15:35.960 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:21:24.367 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:27:14.908 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:33:08.839 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:46:16.220 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:49:20.031 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:49:55.317 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:49:59.108 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:49:59.275 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:49:59.576 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:49:59.576 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:49:59.576 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:49:59.576 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:50:11.638 INFO trying parameters memory cache for: ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:50:11.638 INFO no params in memory cache for ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 20 00:50:11.645 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 33554432; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 20 00:50:11.646 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.params" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 20 00:50:11.646 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.params" for parameters, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:239 storage_proofs::parameter_cache
Jul 20 00:50:28.463 INFO read parameters from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.params" , target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:242 storage_proofs::parameter_cache
Jul 20 00:50:28.463 INFO got groth params (1073741824) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 00:52:10.719 INFO trying parameters memory cache for: ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:52:10.725 INFO no params in memory cache for ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:52 filecoin_proofs::caches
Jul 20 00:52:10.725 INFO parameter set identifier for cache: layered_drgporep::PublicParams{ graph: zigzag_graph::ZigZagGraph{expansion_degree: 8 base_graph: drgraph::BucketGraph{size: 33554432; degree: 5; hasher: PedersenHasher} }, sloth: 0, challenges: Tapered { layers: 4, count: 2, taper: 0.3333333333333333, taper_layers: 2 } }, target: params, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:171 storage_proofs::parameter_cache
Jul 20 00:52:10.725 INFO ensuring that all ancestor directories for: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.vk" exist, target: cache, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:126 storage_proofs::parameter_cache
Jul 20 00:52:10.725 INFO checking cache_path: "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.vk" for verifying key, target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:251 storage_proofs::parameter_cache
Jul 20 00:52:10.753 INFO read verifying key from cache "/var/tmp/filecoin-proof-parameters/v10-zigzag-proof-of-replication-5077e86c9514911753a8755347379b2118e2ebdea4e01fc0c1e7a66bae22ed48.vk" , target: verifying_key, root: storage-proofs, place: storage-proofs/src/parameter_cache.rs:254 storage_proofs::parameter_cache
Jul 20 00:52:10.753 INFO got verifying key (1073741824) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1073741824B (padded) sector
writing 200B to piece-file
generating piece commitment for 1016B piece
writing 200B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 20 00:52:12.120 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:12.120 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:12.121 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:12.121 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:12.123 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:12.123 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:12.123 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:12.123 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:12.123 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:12.154 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:12.154 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:12.154 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:12.155 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:12.155 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:52:12.155 INFO found params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 00:52:12.155 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 00:52:53.250 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:52:53.250 INFO found params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 00:52:53.250 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 4240B to piece-file
generating piece commitment for 16256B piece
writing 4240B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 20 00:52:53.293 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:53.298 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:53.302 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:53.306 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 00:52:53.325 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:53.325 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:53.326 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 00:52:53.354 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:52:53.354 INFO found params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 00:52:53.355 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 00:53:41.889 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 00:53:41.889 INFO found params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 00:53:41.889 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
writing 92889374B to piece-file
generating piece commitment for 266338304B piece
writing 92889374B (unpadded) to 268435456B (padded) sector
sealing 268435456B (padded) sector
Jul 20 00:58:46.789 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:00:09.654 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:01:34.193 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:03:00.264 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:07:05.890 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 01:07:12.427 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 01:07:17.721 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 01:07:18.092 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 01:07:18.179 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 01:07:18.192 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 01:07:18.192 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 01:07:18.192 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 01:07:18.193 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 01:08:04.712 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 01:08:04.712 INFO found params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 01:08:04.712 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 01:09:44.435 INFO trying parameters memory cache for: ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 01:09:44.435 INFO found params in memory cache for ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 01:09:44.435 INFO got verifying key (268435456) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 268435456B (padded) sector
writing 515384169B to piece-file
generating piece commitment for 1065353216B piece
writing 515384169B (unpadded) to 1073741824B (padded) sector
sealing 1073741824B (padded) sector
Jul 20 01:30:16.451 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:35:56.015 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:41:45.451 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 01:47:41.638 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:03:04.259 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:04:10.689 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:05:00.817 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:05:06.086 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:05:07.206 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:05:07.511 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:05:07.511 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:05:07.511 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:05:07.511 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:08:21.465 INFO trying parameters memory cache for: ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:08:21.466 INFO found params in memory cache for ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:08:21.466 INFO got groth params (1073741824) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 02:10:04.157 INFO trying parameters memory cache for: ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:10:04.157 INFO found params in memory cache for ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:10:04.157 INFO got verifying key (1073741824) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1073741824B (padded) sector
writing 68B to piece-file
generating piece commitment for 1016B piece
writing 68B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 20 02:10:05.827 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:05.828 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:05.828 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:05.828 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:05.830 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:05.830 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:05.831 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:05.832 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:10:05.832 INFO found params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:10:05.832 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 02:10:47.169 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:10:47.169 INFO found params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:10:47.169 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 10476B to piece-file
generating piece commitment for 16256B piece
writing 10476B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 20 02:10:47.232 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:47.236 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:47.241 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:47.245 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:10:47.264 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:47.266 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:47.266 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:47.266 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:47.281 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:10:47.281 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:47.281 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:47.282 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:47.282 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:10:47.282 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:10:47.282 INFO found params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:10:47.282 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 02:11:35.847 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:11:35.847 INFO found params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:11:35.847 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
writing 106454533B to piece-file
generating piece commitment for 266338304B piece
writing 106454533B (unpadded) to 268435456B (padded) sector
sealing 268435456B (padded) sector
Jul 20 02:16:42.214 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:18:05.227 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:19:29.842 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:20:55.423 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 02:25:00.998 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:25:02.580 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:25:10.903 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:25:11.420 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:25:11.715 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 02:25:11.725 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:25:11.725 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:25:11.726 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:25:11.726 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 02:25:58.805 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:25:58.806 INFO found params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:25:58.806 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 02:27:37.883 INFO trying parameters memory cache for: ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 02:27:37.883 INFO found params in memory cache for ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 02:27:37.883 INFO got verifying key (268435456) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 268435456B (padded) sector
writing 1007851055B to piece-file
generating piece commitment for 1065353216B piece
writing 1007851055B (unpadded) to 1073741824B (padded) sector
sealing 1073741824B (padded) sector
Jul 20 03:08:38.450 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:14:15.982 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:20:06.544 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:25:52.959 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:42:37.314 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:43:07.174 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:43:20.902 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:43:25.325 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:43:25.432 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:43:25.525 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:43:25.525 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:43:25.525 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:43:25.525 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:49:48.366 INFO trying parameters memory cache for: ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:49:48.366 INFO found params in memory cache for ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:49:48.366 INFO got groth params (1073741824) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 03:51:30.186 INFO trying parameters memory cache for: ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:51:30.192 INFO found params in memory cache for ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:51:30.192 INFO got verifying key (1073741824) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1073741824B (padded) sector
writing 71B to piece-file
generating piece commitment for 1016B piece
writing 71B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 20 03:51:31.288 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:51:31.289 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:51:31.289 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:51:31.289 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:51:31.289 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:51:31.290 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:51:31.291 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:51:31.292 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:51:31.292 INFO found params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:51:31.292 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 03:52:12.112 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:52:12.112 INFO found params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:52:12.112 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 10859B to piece-file
generating piece commitment for 16256B piece
writing 10859B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 20 03:52:12.175 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:52:12.181 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:52:12.183 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:52:12.189 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:52:12.210 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:52:12.219 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:52:12.220 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 03:52:12.220 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:52:12.220 INFO found params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:52:12.220 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 03:53:00.445 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 03:53:00.445 INFO found params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 03:53:00.445 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
writing 13045222B to piece-file
generating piece commitment for 266338304B piece
writing 13045222B (unpadded) to 268435456B (padded) sector
sealing 268435456B (padded) sector
Jul 20 03:53:39.099 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:55:03.807 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:56:28.508 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:57:53.640 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 03:59:09.572 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:01:55.303 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:01:59.151 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:02:00.608 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:02:02.121 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:02:02.132 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:02:02.132 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:02:02.132 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:02:02.132 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:02:08.030 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 04:02:08.030 INFO found params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 04:02:08.030 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 04:03:46.293 INFO trying parameters memory cache for: ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 04:03:46.293 INFO found params in memory cache for ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 04:03:46.293 INFO got verifying key (268435456) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 268435456B (padded) sector
writing 403504729B to piece-file
generating piece commitment for 1065353216B piece
writing 403504729B (unpadded) to 1073741824B (padded) sector
sealing 1073741824B (padded) sector
Jul 20 04:23:59.123 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 04:29:33.335 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 04:35:18.055 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 04:41:08.632 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 04:55:19.359 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:58:03.460 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:58:07.195 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:58:07.975 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:58:08.196 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 04:58:08.237 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:58:08.237 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:58:08.237 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 04:58:08.237 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:01:14.001 INFO trying parameters memory cache for: ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:01:14.002 INFO found params in memory cache for ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:01:14.002 INFO got groth params (1073741824) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 05:02:55.521 INFO trying parameters memory cache for: ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:02:55.521 INFO found params in memory cache for ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:02:55.521 INFO got verifying key (1073741824) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1073741824B (padded) sector
writing 874B to piece-file
generating piece commitment for 1016B piece
writing 874B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 20 05:02:56.696 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:02:56.696 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:02:56.696 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:02:56.697 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:02:56.698 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:02:56.744 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:02:56.745 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:02:56.745 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:02:56.745 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:02:56.745 INFO found params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:02:56.745 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 05:03:37.415 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:03:37.415 INFO found params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:03:37.415 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 7107B to piece-file
generating piece commitment for 16256B piece
writing 7107B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 20 05:03:37.476 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:03:37.482 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:03:37.486 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:03:37.493 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:03:37.508 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:03:37.511 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:03:37.515 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:03:37.516 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:03:37.516 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:03:37.516 INFO found params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:03:37.518 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 05:04:25.573 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:04:25.573 INFO found params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:04:25.573 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
writing 246075096B to piece-file
generating piece commitment for 266338304B piece
writing 246075096B (unpadded) to 268435456B (padded) sector
sealing 268435456B (padded) sector
Jul 20 05:14:36.045 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:15:57.618 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:17:21.104 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:18:45.481 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:22:23.373 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:23:07.602 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:23:08.441 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:23:08.478 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:23:08.506 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 05:23:08.519 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:23:08.519 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:23:08.519 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:23:08.519 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 05:24:43.557 INFO trying parameters memory cache for: ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:24:43.557 INFO found params in memory cache for ZIGZAG[268435456], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:24:43.557 INFO got groth params (268435456) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 05:26:21.689 INFO trying parameters memory cache for: ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 05:26:21.689 INFO found params in memory cache for ZIGZAG[268435456]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 05:26:21.689 INFO got verifying key (268435456) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 268435456B (padded) sector
writing 276540811B to piece-file
generating piece commitment for 1065353216B piece
writing 276540811B (unpadded) to 1073741824B (padded) sector
sealing 1073741824B (padded) sector
Jul 20 05:46:21.131 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:51:56.073 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 05:57:39.500 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:03:29.317 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:19:41.796 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:20:16.627 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:20:16.638 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:20:16.688 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:20:18.261 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:20:18.567 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:20:18.567 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:20:18.567 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:20:18.567 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:23:15.669 INFO trying parameters memory cache for: ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:23:15.670 INFO found params in memory cache for ZIGZAG[1073741824], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:23:15.670 INFO got groth params (1073741824) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 06:24:57.452 INFO trying parameters memory cache for: ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:24:57.452 INFO found params in memory cache for ZIGZAG[1073741824]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:24:57.452 INFO got verifying key (1073741824) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1073741824B (padded) sector
writing 747B to piece-file
generating piece commitment for 1016B piece
writing 747B (unpadded) to 1024B (padded) sector
sealing 1024B (padded) sector
Jul 20 06:24:58.881 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:24:58.882 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:24:58.882 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:24:58.883 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:24:58.884 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:24:58.884 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:24:58.915 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:24:58.915 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:24:58.915 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:24:58.915 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:24:58.916 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:24:58.916 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:24:58.916 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:24:58.916 INFO trying parameters memory cache for: ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:24:58.916 INFO found params in memory cache for ZIGZAG[1024], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:24:58.916 INFO got groth params (1024) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 06:25:39.579 INFO trying parameters memory cache for: ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:25:39.580 INFO found params in memory cache for ZIGZAG[1024]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:25:39.580 INFO got verifying key (1024) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 1024B (padded) sector
writing 15117B to piece-file
generating piece commitment for 16256B piece
writing 15117B (unpadded) to 16384B (padded) sector
sealing 16384B (padded) sector
Jul 20 06:25:39.653 INFO encoding, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:25:39.658 INFO encoding, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:25:39.663 INFO encoding, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:25:39.668 INFO encoding, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:499 storage_proofs::layered_drgporep
Jul 20 06:25:39.687 INFO returning tree, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:25:39.695 INFO returning tree, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:25:39.695 INFO returning tree, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:25:39.695 INFO returning tree, layer: 4, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:25:39.695 INFO returning tree, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:490 storage_proofs::layered_drgporep
Jul 20 06:25:39.696 INFO setting tau/aux, layer: 0, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:25:39.696 INFO setting tau/aux, layer: 1, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:25:39.696 INFO setting tau/aux, layer: 2, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:25:39.696 INFO setting tau/aux, layer: 3, root: storage-proofs, place: storage-proofs/src/layered_drgporep.rs:528 storage_proofs::layered_drgporep
Jul 20 06:25:39.697 INFO trying parameters memory cache for: ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:25:39.697 INFO found params in memory cache for ZIGZAG[16384], target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:25:39.698 INFO got groth params (16384) while sealing, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:253 filecoin_proofs::api
Jul 20 06:26:27.858 INFO trying parameters memory cache for: ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:42 filecoin_proofs::caches
Jul 20 06:26:27.858 INFO found params in memory cache for ZIGZAG[16384]-verifying-key, target: params, root: filecoin-proofs, place: filecoin-proofs/src/caches.rs:47 filecoin_proofs::caches
Jul 20 06:26:27.858 INFO got verifying key (16384) while verifying seal, target: params, root: filecoin-proofs, place: filecoin-proofs/src/api.rs:358 filecoin_proofs::api
verifying PIPs generated when sealing 16384B (padded) sector
```

File: filecoin-proofs/src/api.rs [hunk 1]
```diff
@@ -762,38 +762,40 @@ mod tests {
     #[test]
     #[ignore]
     fn test_pip_lifecycle() -> Result<(), failure::Error> {
-        let number_of_bytes_in_piece: u64 = 500;
-        let unpadded_number_of_bytes_in_piece = UnpaddedBytesAmount(number_of_bytes_in_piece);
-        let bytes: Vec<u8> = (0..number_of_bytes_in_piece)
+        // This size is a minimal repro for the P0 API sanity check failure.
+        let sector_size = 1 << 14;
```
Comment (laser) [inline filecoin-proofs/src/api.rs]: @porcuquine 

Using a sector of `1 << 14` size here is going to trigger the lazy Groth parameter generation flow when the `test_ignored_release` CircleCI build runs. Longer builds and all that.

Do you mind if I change `let sector_size = 1 << 14;` to `let sector_size = TEST_SECTOR_SIZE;`? I realize that the old bug wouldn't manifest with 1024B sectors and I'm not concerned about that.

File: filecoin-proofs/src/api.rs [hunk 2]
```diff
@@ -277,7 +277,7 @@ pub fn seal<T: AsRef<Path>>(
             .into_iter()
             .map(|p| p.number_of_leaves)
             .collect::<Vec<_>>(),
-        (sector_bytes / 127) * 4,
+        sector_bytes >> 5,
```
Comment (laser) [inline filecoin-proofs/src/api.rs]: Note for @sidke - Before this changeset, this code had only been exercised with 1024B (bit-padded) sectors. So, by virtue of the way that division with `usize` is handled in Rust, things worked as intended (with 1024B sectors):

```
(sector_bytes / 127) * 4 == floor(1024 / 127) * 4
                         == floor(8.06299) * 4
                         == 8 * 4
                         == 32
```
